version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./apps/backend:/app
    environment:
      - FLASK_ENV=development
  frontend:
    build:
      context: .
      dockerfile: docker/frontend.Dockerfile
    ports:
      - "5173:80"
    volumes:
      - ./apps/frontend:/usr/share/nginx/html 